import type { Config } from 'tailwindcss'

const config: Config = {
  content: [
    './app/**/*.{ts,tsx}',
    './components/**/*.{ts,tsx}',
    './lib/**/*.{ts,tsx}',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'surface':                    '#131313',
        'surface-dim':                '#131313',
        'surface-bright':             '#393939',
        'surface-container-lowest':   '#0e0e0e',
        'surface-container-low':      '#1b1b1b',
        'surface-container':          '#1f1f1f',
        'surface-container-high':     '#2a2a2a',
        'surface-container-highest':  '#353535',
        'surface-variant':            '#353535',
        'on-surface':                 '#e2e2e2',
        'on-surface-variant':         '#ebbbb4',
        'background':                 '#131313',
        'on-background':              '#e2e2e2',
        'primary':                    '#ffb4a8',
        'primary-container':          '#ff5540',
        'primary-fixed':              '#ffdad4',
        'primary-fixed-dim':          '#ffb4a8',
        'on-primary':                 '#690100',
        'on-primary-container':       '#5c0000',
        'on-primary-fixed':           '#410000',
        'on-primary-fixed-variant':   '#930100',
        'inverse-primary':            '#c00100',
        'secondary':                  '#c4c6cc',
        'secondary-container':        '#46494e',
        'on-secondary':               '#2d3135',
        'on-secondary-container':     '#b6b8be',
        'tertiary':                   '#c4c7c5',
        'tertiary-container':         '#8e9190',
        'on-tertiary':                '#2d3130',
        'on-tertiary-container':      '#272a29',
        'error':                      '#ffb4ab',
        'error-container':            '#93000a',
        'on-error':                   '#690005',
        'on-error-container':         '#ffdad6',
        'outline':                    '#b18780',
        'outline-variant':            '#603e39',
        'inverse-surface':            '#e2e2e2',
        'inverse-on-surface':         '#303030',
        success: '#10B981',
        warning: '#F59E0B',
        danger:  '#EF4444',
      },
      fontFamily: {
        headline: ['"Space Grotesk"', 'system-ui', 'sans-serif'],
        body:     ['Inter', 'system-ui', 'sans-serif'],
        label:    ['"Space Grotesk"', 'system-ui', 'sans-serif'],
        mono:     ['"JetBrains Mono"', 'Menlo', 'monospace'],
      },
      borderRadius: {
        DEFAULT: '0px',
        none:    '0px',
        sm:      '0px',
        md:      '0px',
        lg:      '0px',
        xl:      '0px',
        '2xl':   '0px',
        full:    '9999px',
      },
    },
  },
  plugins: [],
}

export default config
